// Motivational Quotes
const quotes = [
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Remember why you started.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are stronger than you think.",
  "It always seems impossible until it is done. - Nelson Mandela",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "Positive thinking will let you do everything better than negative thinking will. - Zig Ziglar",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "If you want to achieve greatness, stop asking for permission. - Unknown",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
  "Accept the challenges so that you can feel the exhilaration of victory. - George S. Patton",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The will to win, the desire to succeed, the urge to reach your full potential… these are the keys that will unlock the door to personal excellence. - Confucius",
  "Don’t wait for extraordinary opportunities. Seize common occasions and make them great. - Orison Swett Marden",
  "Believe you can and you’re halfway there. - Theodore Roosevelt",
  "The harder you work, the luckier you get. - Gary Player",
  "It’s not whether you get knocked down. It’s whether you get up. - Vince Lombardi",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Your imagination is your preview of life’s coming attractions. - Albert Einstein",
  "Dream big and dare to fail. - Norman Vaughan",
  "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you. - George Whitefield",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others. - Ayn Rand",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got to keep going. - Chantal Sutherland",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "Good. Better. Best. Never let it rest. ‘Til your good is better and your better is best. - St. Jerome",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "If you can dream it, you can do it. - Walt Disney",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It’s not whether you get knocked down. It’s whether you get up. - Vince Lombardi",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
  "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "If you can dream it, you can do it. - Walt Disney",
  "It’s not whether you get knocked down. It’s whether you get up. - Vince Lombardi",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
];